### ISSUE TITLE
Can't get it running

### ISSUE THREAD

**Issue by ertarta** [SimCMinMax/AutoSimC#20]
Hello, 
I am no expert in the field but I have followed (and tried again, and again, and again) all the syntax and it seems to be fine. The problem is: when I copy my chacacter codes into the input.txt it won't even launch, The bat will open and close. When I paste in the default pg data (the druid that comes with it as dummy profile) it werks. It must be some kind of problem with the communication between autosimc and simulationcraft at this point but I really don't know what to do, can you please help me?
Thank you in advance

**Comment by scamille** [comment]
1)
Please run launch.bat from a command line shell (cmd.exe or PowerShell). An easy way to do so is if you are in the AutoSimC folder, Shift-Rightclick and select "Open PowerShell window here". Then run ./launch.bat

That way you will retain any error messages and can easily copy them here.
Thus run again and check what error messages you get, post them or a screenshot here please.

2)
You can also check the logs.txt in your AutoSimC folder. And maybe post the input.txt you created here as well, so we can try to reproduce the problem.

**Comment by ertarta** [comment]
File "C:\AutoSimC-master\main.py", line 1433, in <module>
    main()
  File "C:\AutoSimC-master\main.py", line 1407, in main
    raise ValueError("No valid profile combinations found."
ValueError: No valid profile combinations found. Please run again with --debug and check your input.txt and settings.py.
2017-12-10 09:14:49,191 INFO Analyzer-file found at 'C:\AutoSimC-master\profiles\Analysis.json'.
2017-12-10 09:14:49,192 INFO SimC options: {'race': 'undead', 'level': '110', 'spec': 'affliction', 'role': 'spell', 'position': 'back', 'artifact': '39:0:0:0:0:915:4:916:4:917:4:918:4:919:4:920:4:921:4:922:4:923:4:924:1:925:1:926:1:927:1:928:1:929:1:999:1:1353:1:1390:1:1601:4:1602:1:1603:1:1604:24:1711:1', 'crucible': '1739:1775:920/1739:1781:915/1739:1782:918'}
2017-12-10 09:14:49,194 INFO Parsed gear including legendaries:
2017-12-10 09:14:49,194 INFO head      : [Item(head=,id=147183,bonus_id=3562/1497/3528)]
2017-12-10 09:14:49,194 INFO neck      : [Item(neck=,id=147014,bonus_id=3561/1512/3337,enchant_id=5890)]
2017-12-10 09:14:49,194 INFO shoulders : [Item(shoulders=,id=147186,bonus_id=3562/40/1502/3336,enchant_id=5929)]
2017-12-10 09:14:49,194 INFO back      : [Item(back=,id=146984,bonus_id=3562/1522/3337,enchant_id=5436)]
2017-12-10 09:14:49,194 INFO chest     : [Item(chest=,id=142147,bonus_id=3536/42/1577/3337)]
2017-12-10 09:14:49,194 INFO wrists    : [Item(wrists=,id=139130,bonus_id=3536/1622/3337)]
2017-12-10 09:14:49,194 INFO hands     : [Item(hands=,id=147182,bonus_id=3563/1512/3528)]
2017-12-10 09:14:49,194 INFO waist     : [Item(waist=,id=132457,bonus_id=3459/3630)]
2017-12-10 09:14:49,194 INFO legs      : [Item(legs=,id=147184,bonus_id=3562/1502/3336)]
2017-12-10 09:14:49,194 INFO feet      : [Item(feet=,id=151940,bonus_id=3610/1472/3528)]
2017-12-10 09:14:49,195 INFO finger    : [Item(finger=,id=132378,bonus_id=3529/1811/3630,enchant_id=5428,gem_id=151583), Item(finger=,id=147195,bonus_id=3562/1522/3337,enchant_id=5428)]
2017-12-10 09:14:49,195 INFO trinket   : [Item(trinket=,id=121311,bonus_id=3573/1808/604/1572/3528,gem_id=151583), Item(trinket=,id=147017,bonus_id=3562/1497/3528)]
2017-12-10 09:14:49,195 INFO main_hand : [Item(main_hand=,id=128942,bonus_id=747,gem_id=151294/152028/155852,relic_id=3418:1587:3337/3611:1492:3336/3610:1482:3528)]
2017-12-10 09:14:49,195 INFO off_hand  : [Item(off_hand=,id=0)]
2017-12-10 09:14:49,195 INFO Got 1 permutations for finger after unique filter.
2017-12-10 09:14:49,195 INFO Got 1 permutations for trinket after unique filter.
2017-12-10 09:14:49,196 INFO Got 1 permutations for trinkets after Antorus filter.
2017-12-10 09:14:49,196 INFO Max number of normal permutations: 1
2017-12-10 09:14:49,196 INFO Number of permutations: {'normal gear&talents': "1 ({'head': 1, 'neck': 1, 'shoulders': 1, 'back': 1, 'chest': 1, 'wrists': 1, 'hands': 1, 'waist': 1, 'legs': 1, 'feet': 1, 'main_hand': 1, 'off_hand': 1})", 'finger': 1, 'trinket': 1, 'talents': 1}
2017-12-10 09:14:49,196 INFO Processed 1/1 (100.00%) valid 0 ( 0.00%) elapsed_time 0:00:00 remaining 0:00:00 bw 2k/s bw(valid) 0k/s
2017-12-10 09:14:49,196 INFO Finished permutations. Valid: 0 of 1 processed. (0.00%)
2017-12-10 09:14:49,197 INFO Output file checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2017-12-10 09:14:49,197 INFO Permutating took 0:00:00.004505.
2017-12-10 09:14:49,198 ERROR Error: No valid profile combinations found. Please run again with --debug and check your input.txt and settings.py.
Traceback (most recent call last):
  File "C:\AutoSimC-master\main.py", line 1433, in <module>
    main()
  File "C:\AutoSimC-master\main.py", line 1407, in main
    raise ValueError("No valid profile combinations found."
ValueError: No valid profile combinations found. Please run again with --debug and check your input.txt and settings.py.

**Comment by scamille** [comment]
The error message say it all: Even though there has been 1 combination created (which is not really what AutoSimC is there for, you usually want to create thousands of combinations), this 1 profile was not deemed valid.

If you run with --debug attached as an argument in your launch.bat, AutoSimC will stored and print out the reasons for your profile(s) not being valid. Eg. too few legendaries, not enough/too many tier items, etc.
