### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jacho981** [SimCMinMax/AutoSimC#36]
i just pasted simpermut's "Autosim export" string into input file, and run launch.bat. i get this error:

```
Python.exe exists. Launching AutoSimC!
--If you get the message: "cant open file "main.py" [Errno2].."
--Please add Python-Path to your Systemvariables-Path-Variable
--https://i.imgur.com/KM132c7.png
----------------------------------------------------------------
No translation for ['es_ES'] available.
AutoSimC - Supported WoW-Version: 8.0.1a
Starting auto download check of SimulationCraft.
Latest simc: simc-801-02-win64-a707690b9d.7z
Simc already exists at ''C:\\Users\\*****\\Desktop\\AutoSimC-master\\auto_download\\simc-801-02-win64\\simc.exe''.
Analyzer-file found at 'C:\Users\*****\Desktop\AutoSimC-master\profiles\Analysis.json'.
SimC options: {'spec': 'frost', 'level': '120', 'race': 'dwarf', 'role': 'spell', 'position': 'back', 'talents': '1213133'}
Combinations in progress...
Error: list index out of range
Traceback (most recent call last):
  File "main.py", line 1558, in <module>
    main()
  File "main.py", line 1519, in main
    num_generated_profiles = permutate(args, player_profile)
  File "main.py", line 961, in permutate
    currentGear = gear[b][0]
IndexError: list index out of range
Presione una tecla para continuar . . .
```

**Comment by redi-tormeyd** [comment]
I see this same issue when importing a simc profile that only has a main_hand= entry defined.  I've been able to work around this by adding a line like:
    `off_hand=0`

**Comment by jacho981** [comment]
yeah, i only have a staff as a weapon, will try that. where do i add that line? after the main hand line? thx

EDIT:
there's no such "main_hand" in my sim_permut string

```
[Profile]
mage=Peinarratas
spec=frost
level=120
race=dwarf
role=spell
position=back
talents=1213133


[Gear]
head=,id=160616,bonus_id=4823/1492/4786
neck=,id=158075,bonus_id=4936/4929/4930/1518
shoulder=,id=158035,bonus_id=1532/5140
back=,id=160642,bonus_id=4799/1492/4786|,id=158375,bonus_id=5009/42/1547/4783
chest=,id=160614,bonus_id=4823/1492/4786
wrist=,id=159275,bonus_id=5010/1552/4783|,id=159282,bonus_id=5010/1552/4783|,id=158348,enchant_id=5971,bonus_id=5008/4802/1537/4786,gem_id=
hands=,id=160612,bonus_id=4800/1512/4783
waist=,id=160727,bonus_id=4799/1492/4786|,id=158346,bonus_id=5010/1542/4786|,id=159965,bonus_id=5010/4802/1542/4786,gem_id=|,id=159226,bonus_id=5010/1542/4786
legs=,id=158350,bonus_id=5010/1552/4783
feet=,id=159243,bonus_id=5009/4802/1537/4786,gem_id=
finger1=,id=162541,enchant_id=5943,bonus_id=5010/4802/1542/4786,gem_id=|,id=159461,enchant_id=5943,bonus_id=5008/40/1537/4786|,id=158314,enchant_id=5943,bonus_id=5008/4802/42/1527/4786,gem_id=|,id=158362,enchant_id=5943,bonus_id=5010/1542/4786|,id=159459,enchant_id=5943,bonus_id=5006/1527/4786|,id=159461,enchant_id=5943,bonus_id=5010/1542/4786
finger2=,id=162541,enchant_id=5943,bonus_id=5010/4802/1542/4786,gem_id=|,id=159461,enchant_id=5943,bonus_id=5008/40/1537/4786|,id=158314,enchant_id=5943,bonus_id=5008/4802/42/1527/4786,gem_id=|,id=158362,enchant_id=5943,bonus_id=5010/1542/4786|,id=159459,enchant_id=5943,bonus_id=5006/1527/4786|,id=159461,enchant_id=5943,bonus_id=5010/1542/4786
trinket1=,id=159620,bonus_id=5010/40/1542/4786|,id=159624,bonus_id=5009/40/1547/4783|,id=163937,bonus_id=1472/4786|,id=159631,bonus_id=5010/4802/1542/4786,gem_id=|,id=159630,bonus_id=5010/1542/4786
trinket2=,id=159620,bonus_id=5010/40/1542/4786|,id=159624,bonus_id=5009/40/1547/4783|,id=163937,bonus_id=1472/4786|,id=159631,bonus_id=5010/4802/1542/4786,gem_id=|,id=159630,bonus_id=5010/1542/4786

```

wierd af, the equipped weapon shoul've been listed. will double check

EDIT 2:
AutoSim Export is not exporting the main hand in the string, even when it's selected :/ so RIP

**Comment by jacho981** [comment]
ok yeah, the addon is broken, so rip

"Addon is broken right now, i'm working on fixing it but it could take a bit of time."
