### ISSUE TITLE
SimulationCraft error! Worker #2 returned error code 1.

### ISSUE THREAD

**Issue by Frolic3290** [SimCMinMax/AutoSimC#40]
Hello,

I hope I'm in the correct section here.

I have set up AutoSimC according to your tutorial. I'm using SimPermut for the Data Export.
I double checked that the import.txt is in the UTF-8 Coding and that the paths in the settings.py are correct.
I am NOT pointing to the Simulationcraft GUI, but to the simc.exe

- I run the launch.bat
- I select "2" Default_LightMovement
- I select "2" Dynamic mode

And then this error occurs.

2018-11-02 01:09:08,203 ERROR SimulationCraft error! Worker #1 returned error code 1.
2018-11-02 01:09:08,203 ERROR SimulationCraft error! Worker #0 returned error code 1.
2018-11-02 01:09:08,203 ERROR Error: 'bytes' object has no attribute 'read'
Traceback (most recent call last):
  File "main.py", line 1564, in <module>
    main()
  File "main.py", line 1551, in main
    start_stage(player_profile, num_generated_profiles, 1)
  File "main.py", line 1382, in start_stage
    dynamic_stage(player_profile, num_generated_profiles, None, stage)
  File "main.py", line 1350, in dynamic_stage
    stage, is_last_stage, num_generated_profiles)
  File "C:\AutoSimC\splitter.py", line 278, in simulate
    result = _start_simulation(files, player_profile, simtype, simtype_value, stage, is_last_stage, num_profiles)
  File "C:\AutoSimC\splitter.py", line 265, in _start_simulation
    return _launch_simc_commands(commands, is_last_stage)
  File "C:\AutoSimC\splitter.py", line 213, in _launch_simc_commands
    r = int(future.result())
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\AutoSimC\splitter.py", line 185, in _worker
    logging.info("SimulationCraft #{} stderr: \n{}".format(counter, p.stderr.read().decode()))
AttributeError: 'bytes' object has no attribute 'read'
2018-11-02 01:09:08,208 ERROR SimulationCraft error! Worker #2 returned error code 1.
2018-11-02 01:09:08,211 ERROR SimulationCraft error! Worker #4 returned error code 1.
2018-11-02 01:09:08,215 ERROR SimulationCraft error! Worker #3 returned error code 1.
2018-11-02 01:09:08,299 ERROR SimulationCraft error! Worker #6 returned error code 1.
2018-11-02 01:09:08,365 ERROR SimulationCraft error! Worker #7 returned error code 1.
2018-11-02 01:09:08,365 ERROR SimulationCraft error! Worker #5 returned error code 1.
2018-11-02 01:09:08,369 ERROR SimulationCraft error! Worker #9 returned error code 1.
2018-11-02 01:09:08,374 ERROR SimulationCraft error! Worker #8 returned error code 1.
2018-11-02 01:09:08,459 ERROR SimulationCraft error! Worker #10 returned error code 1.
2018-11-02 01:09:08,518 ERROR SimulationCraft error! Worker #12 returned error code 1.
2018-11-02 01:09:08,520 ERROR SimulationCraft error! Worker #11 returned error code 1.
2018-11-02 01:09:08,521 ERROR SimulationCraft error! Worker #13 returned error code 1.
2018-11-02 01:09:08,530 ERROR SimulationCraft error! Worker #14 returned error code 1.

I attatched my input.txt, the error.txt and the whole log.txt
Please let me know if you need further informations.
[error.txt](https://github.com/SimCMinMax/AutoSimC/files/2540574/error.txt)
[logs.txt](https://github.com/SimCMinMax/AutoSimC/files/2540575/logs.txt)
[input.txt](https://github.com/SimCMinMax/AutoSimC/files/2540576/input.txt)

**Comment by theoneandlonely** [comment]
Hi Ghostsierra,

development of Simpermut has stopped after BfA-release. Therefore the input-generation and -parsing has been moved to match the output the simulationcraft-ingame-addon generates.
The error is therefore correct -> the input.txt-format is simply outdated now.

**Comment by Frolic3290** [comment]
> 
> 
> Hi Ghostsierra,
> 
> development of Simpermut has stopped after BfA-release. Therefore the input-generation and -parsing has been moved to match the output the simulationcraft-ingame-addon generates.
> The error is therefore correct -> the input.txt-format is simply outdated now.

Hello,

thank you for your answer. I did try it with the Simcraft addon. I recieve almost the same results.
It is simulatting with a few error returns. And when it comes do 100% it simply decides to abort with a final Worker Error message. I can do nothing exept "pressing any button to exit".

Heres my input, error and logfile.
I double checked again for the UTF-8 Coding.
I hope you can find something
[error.txt](https://github.com/SimCMinMax/AutoSimC/files/2546757/error.txt)
[input.txt](https://github.com/SimCMinMax/AutoSimC/files/2546758/input.txt)
[logs.txt](https://github.com/SimCMinMax/AutoSimC/files/2546759/logs.txt)

**Comment by theoneandlonely** [comment]
Hi Ghostsierra,

try again without simulating with fishing-rods, tabards (lets face it: you dont hit harder when wearing your pink-brown guildies-tabard :D), and without the ghost-helmet.

Simulation stopped here when i left the fishing rod in input.txt; by removing these useless items you drastically increase your computing-time, anyway.

**Comment by Frolic3290** [comment]
> 
> 
> Hi Ghostsierra,
> 
> try again without simulating with fishing-rods, tabards (lets face it: you dont hit harder when wearing your pink-brown guildies-tabard :D), and without the ghost-helmet.
> 
> Simulation stopped here when i left the fishing rod in input.txt; by removing these useless items you drastically increase your computing-time, anyway.

Oh jesus... Yes it absoluteley makes sense that Errors happen with a damn fishing rod. I knew I had them in the Bag but I didn't thought about the possibillity that it might results in errors.
Thank you very much! :-)
