### ISSUE TITLE
hero 

### ISSUE THREAD

**Issue by Nexxxy** [SimCMinMax/AutoSimC#42]
Default_HeroDungeon crashes with 
SimulationCraft error! Worker #2 returned error code 1.
Error: 'bytes' object has no attribute 'read'
Traceback (most recent call last):
  File "main.py", line 1564, in <module>
    main()
  File "main.py", line 1551, in main
    start_stage(player_profile, num_generated_profiles, 1)
  File "main.py", line 1382, in start_stage
    dynamic_stage(player_profile, num_generated_profiles, None, stage)
  File "main.py", line 1350, in dynamic_stage
    stage, is_last_stage, num_generated_profiles)
  File "S:\World of Warcraft\pyAutoSimC\splitter.py", line 278, in simulate
    result = _start_simulation(files, player_profile, simtype, simtype_value, stage, is_last_stage, num_profiles)
  File "S:\World of Warcraft\pyAutoSimC\splitter.py", line 265, in _start_simulation
    return _launch_simc_commands(commands, is_last_stage)
  File "S:\World of Warcraft\pyAutoSimC\splitter.py", line 213, in _launch_simc_commands
    r = int(future.result())
  File "C:\Users\Nex0r\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\Nex0r\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\Nex0r\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "S:\World of Warcraft\pyAutoSimC\splitter.py", line 185, in _worker
    logging.info("SimulationCraft #{} stderr: \n{}".format(counter, p.stderr.read().decode()))
AttributeError: 'bytes' object has no attribute 'read'
SimulationCraft error! Worker #0 returned error code 1.
SimulationCraft error! Worker #1 returned error code 1.

Here are my input files + settings
[input.txt](https://github.com/SimCMinMax/AutoSimC/files/2553664/input.txt)
[settings.py.txt](https://github.com/SimCMinMax/AutoSimC/files/2553668/settings.py.txt)

**Comment by theoneandlonely** [comment]
Hi Nexxy,

apparently HeroDungeon is now called DungeonSlice, because...Raider is now Twix...
Its updated now.

**Comment by Nexxxy** [comment]
Hi, yep can confirm its fixed now
